version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: ./gradlew clean build -x signArchives
      - run:
          name: Code coverage
          command: |
            ./gradlew jacocoTestReport
            ./gradlew jacocoTestCoverageVerification
            bash <(curl -s https://codecov.io/bash)
workflows:
  build_and_test:
    jobs:
      - build
